import { DateTime } from "effect"
import type { Provider } from "../../core/src/Domain"

export const TAILINGS_START = "<!-- tailings:start -->"
export const TAILINGS_END = "<!-- tailings:end -->"

/** The digest only needs to know which tool each artifact came from — it counts
 * them, it does not embed their content. */
export type DigestEntry = { readonly provider: Provider }

export type DigestInput = {
  readonly dir: string
  readonly generatedAt: DateTime.Utc
  readonly periodLabel?: string | undefined
  readonly tools: ReadonlyArray<Provider>
  readonly sessions: ReadonlyArray<DigestEntry>
  readonly memories: ReadonlyArray<DigestEntry>
  readonly notes: ReadonlyArray<string>
}

const plural = (count: number, one: string, many: string): string =>
  `${count} ${count === 1 ? one : many}`

type ProviderTally = { readonly provider: Provider; readonly sessions: number; readonly memories: number }

/** Per-provider counts, only for providers that actually have history here. */
const tally = (input: DigestInput): ReadonlyArray<ProviderTally> =>
  input.tools
    .map((provider) => ({
      provider,
      sessions: input.sessions.filter((session) => session.provider === provider).length,
      memories: input.memories.filter((memory) => memory.provider === provider).length
    }))
    .filter((row) => row.sessions > 0 || row.memories > 0)

/**
 * Build the digest block embedded in the target dir's AGENTS.md. It is a
 * *signpost*, not a data dump: it points the next agent at `./.tailings/` and
 * says which tools left history. The actual content stays in `./.tailings/`
 * (gitignored), so AGENTS.md carries no transcript bodies or memory text — there
 * is nothing here for `git commit` to leak.
 */
export const buildDigest = (input: DigestInput): string => {
  const lines: Array<string> = []
  lines.push("# Prior agent context (pulled by Tailings)")
  lines.push("")
  lines.push(
    `Earlier coding-agent sessions ran in \`${input.dir}\`. Their memories and full ` +
      `transcripts were gathered ${DateTime.formatIso(input.generatedAt)}` +
      `${input.periodLabel === undefined ? "" : ` (${input.periodLabel})`} into \`./.tailings/\`.`
  )
  lines.push("")
  lines.push(
    "**Read `./.tailings/` before you start** — a weaker model with this folder beats a " +
      "stronger model starting cold."
  )
  lines.push("")
  lines.push("- `./.tailings/memories/` — what those agents chose to remember (decisions, gotchas, project facts).")
  lines.push("- `./.tailings/sessions/` — full prior transcripts, one markdown file per session.")
  lines.push("")

  const rows = tally(input)
  if (rows.length === 0) {
    lines.push("_No prior agent history was found for this directory yet._")
    lines.push("")
  } else {
    lines.push("Available here:")
    lines.push("")
    for (const row of rows) {
      lines.push(
        `- **${row.provider}** — ${plural(row.sessions, "session", "sessions")}, ` +
          `${plural(row.memories, "memory file", "memory files")}`
      )
    }
    lines.push("")
  }

  if (input.notes.length > 0) {
    lines.push("## Notes")
    lines.push("")
    for (const note of input.notes) lines.push(`- ${note}`)
    lines.push("")
  }

  lines.push("_Generated by [Tailings](https://github.com/WaryaWayne/tailings). Re-run `tailings pull` to refresh._")
  return lines.join("\n").trim()
}

const indicesOf = (haystack: string, needle: string): ReadonlyArray<number> => {
  const out: Array<number> = []
  let from = 0
  while (true) {
    const idx = haystack.indexOf(needle, from)
    if (idx === -1) break
    out.push(idx)
    from = idx + needle.length
  }
  return out
}

/** Splice the digest into an existing AGENTS.md between markers, without
 * clobbering anything the user wrote outside the block. */
export const mergeAgentsMd = (existing: string, digest: string): string => {
  const wrapped = `${TAILINGS_START}\n${digest}\n${TAILINGS_END}`
  const starts = indicesOf(existing, TAILINGS_START)
  const ends = indicesOf(existing, TAILINGS_END)

  // Replace in place only when there's exactly one well-formed managed block.
  // Anything else — an orphan start from an interrupted write, duplicated or
  // misordered markers, or a marker echoed inside a session title — is
  // ambiguous, so we append a fresh block rather than splice across an
  // arbitrary span and delete the user's own text.
  if (starts.length === 1 && ends.length === 1 && starts[0]! < ends[0]!) {
    const start = starts[0]!
    const end = ends[0]!
    return `${existing.slice(0, start)}${wrapped}${existing.slice(end + TAILINGS_END.length)}`
  }
  if (existing.trim().length === 0) return `${wrapped}\n`
  return `${existing.trimEnd()}\n\n${wrapped}\n`
}
